# Generated by Django 5.0.6 on 2024-07-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_select_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='select_time',
            new_name='appointment_time',
        ),
    ]
