# Generated by Django 5.0.6 on 2024-07-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='dortor',
            new_name='doctor',
        ),
    ]
